### PR TITLE
Manfontan patch 1

### PR DESCRIPTION
**Pull request by manfontan**
this is my first patch

### CODE REVIEW

**Comment by manfontan** [comment]
@gabarmas @garyweston @stephendavies this is manuel's pull request

**Comment by kmdtraining** [comment]
:+1:

**Comment by rezwang** [comment]
:+1:

**Comment by garyweston** [comment]
:+1:

**Comment by manfontan** [comment]
#199

**Comment by manfontan** [comment]
this is ready

**Pull request closed without merging**
