### PR TITLE
Create karen-bruzzo.md

### PR DESCRIPTION
**Pull request by karenbruzzo**
creating bio

### CODE REVIEW

**Comment by Cbayless** [comment]
I love Sushi, Great Choice!

**Comment by githubteacher** [comment]
@karenbruzzo I also love :sushi: - where is your favorite sushi restaurant?

**Comment by dan-bowerman** [comment]
@karenbruzzo I love ARBY'S :hamburger:

**Comment by pauljeffreys** [comment]
:sushi:  :dancer:

**Comment by cnmontreal** [comment]
@karenbruzzo i also love ":sushi:" blah blah  ":sushi:"

**Comment by pamkenyon** [comment]
@karenbruzzo I wish the had In-N-Out Burger in my state :-( But I love sushi also!

**Comment by kristiesasser** [comment]
Hmmm raw fish, not my favorite

**Comment by t3hbeowulf** [comment]
Listen!  Do you smell that?

**Comment by ghost** [comment]
Me too

**Comment by ghost** [comment]
:+1:

**Pull request merged**
