### PR TITLE
New bio for srikanthchitipotu

### PR DESCRIPTION
**Pull request by srikanthchitipotu**
Please help me with my bio

### CODE REVIEW

**Comment by sreechandran** [comment]
@srikanthchitipotu really? :question:

**Comment by srikanthchitipotu** [comment]
@sreechandran no just adding something :)

**Comment by srikanthchitipotu** [comment]
@karenbruzzo  added now :smile:

**Comment by gabarmas-ibm** [comment]
:+1:

**Comment by srikanthchitipotu** [comment]
Handled issue #35

**Pull request merged**
