### PR TITLE
Create My BIO

### PR DESCRIPTION
**Pull request by AGottipati**

### CODE REVIEW

**Comment by NDCoder** [comment]
Hello

**Comment by vsheela** [comment]
I don't see mine

**Comment by srikanthchitipotu** [comment]
Please add your favorite place :)

**Comment by HimanshuKeskar1** [comment]
The meaning of life is 42

**Comment by AGottipati** [comment]
Pondicherry, India as in 'HOME'

**Comment by HimanshuKeskar1** [comment]
The meaning of life is 42 - Whatever....

**Comment by HimanshuKeskar1** [comment]
The square root of a negative number is irrational

**Comment by AGottipati** [comment]
- [ ] Sample cehckbox

**Comment by Cbayless** [comment]
the Meaning of life is a thumbs up. can't remember the code

**Comment by srikanthchitipotu** [comment]
:+1:

**Pull request merged**
